language: python

python:
  - "3.4"

before_install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install -y build-essential ca-certificates language-pack-en python-dev cython"
 
install:
  - pip install -U pip
  - pip install coveralls
  - pip install -r requirements-tests.txt
  - pip install --no-deps -e .

before_script:
  - env
  - pip freeze
  
script:
  - nosetests --with-coverage -s -v sdmx_tests
  - flake8 --exit-zero sdmx.py
  
after_script: coveralls --verbose

notifications:
  email: true
  on_success: always
  on_failure: always

  
